name: hexlet-linters
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run setup
        run: make install

      - name: Run eslint
        run: make eslint
